version: 0.2

phases:
  install:
    commands:
      - echo "Starting install phase..."
      - apt-get install -y unzip wget curl  # Installing tools for Terraform
      - echo "Installing Terraform..."
      - TERRAFORM_VERSION="1.10.5"  # Specify the version you want to install
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

  pre_build:
    commands:
      - echo "Starting install pre_build phase..."
      - echo "Starting pre-build phase..."
      - cd ~
      - git clone https://github.com/Maninder1220/WE3-C02-IaC.git
      - pwd
      - cd WE3-C02-IaC/Root
      - terraform init  # Downloading and configuring provider plugins
      - echo "Pre-build phase complete."

  build:
    commands:
      - echo "Starting build phase..."
      - terraform plan -destroy -out=tfplan  # Creating an execution plan for review
      - echo "Build phase complete."
      - pwd
      

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan  # Destroying infrastructure
      - echo "Terraform destroy complete."
      - echo "Post-build phase complete."
