version: 0.0
os: linux
files:
  - source: /WE3-C02-IaC # Adjust this to the Terraform project root folder or specific files
    destination: /opt/terraform-project  # Directory on the EC2 instance
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/01_stop_application.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/02_before_install.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/03_install_dependency.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/04_after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/05_application_start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/06_validate_service.sh
      timeout: 300
      runas: root
