version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/01_stop_application.sh
      timeout: 300  # 5 minutes timeout
      runas: root

# Make sure bundle is downloaded on ec2 instance

  BeforeInstall:
    - location: scripts/02_install_dependencies.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/03_install_application.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/04_configure_permissions.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/05_start_application.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/06_validate_service.sh
      timeout: 300
      runas: root    
