version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Nothing to build for index.html"
  post_build:
    commands:
      - echo "Build process complete"

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/01_stop_application.sh
    - scripts/02_install_dependencies.sh
    - scripts/03_install_application.sh
    - scripts/04_configure_permissions.sh
    - scripts/05_start_application.sh
    - scripts/06_validate_service.sh
